cabal-version:      3.8
build-type:         Simple
name:               reprise
version:            1.0.0.0
license:            BSD-3-Clause
license-file:       LICENSE
category:           Sound
maintainer:         andrzej@rybczak.net
author:             Andrzej Rybczak
synopsis:           A terminal client for the Music Player Daemon.

description:
  A terminal client for the <https://www.musicpd.org Music Player Daemon>
  (MPD), the successor of ncmpcpp.

extra-doc-files:
  CHANGELOG.md
  README.md

extra-source-files:
  tests/golden/*.txt

tested-with: GHC ^>= { 9.6, 9.8, 9.10, 9.12, 9.14 }

bug-reports: https://github.com/arybczak/reprise/issues
source-repository head
  type:     git
  location: https://github.com/arybczak/reprise.git
  subdir:   reprise

common language
    ghc-options:        -Wall
                        -Wcompat
                        -Werror=missing-deriving-strategies
                        -Werror=name-shadowing
                        -Werror=prepositive-qualified-module

    default-language:   GHC2021

    default-extensions: DataKinds
                        DeepSubsumption
                        DerivingStrategies
                        DuplicateRecordFields
                        LambdaCase
                        NoFieldSelectors
                        NoStarIsType
                        OverloadedLabels
                        OverloadedRecordDot
                        OverloadedStrings
                        RoleAnnotations
                        StrictData
                        TypeFamilies
                        UndecidableInstances

library
    import:         language

    build-depends:    base                 >= 4.18      && < 5
                    , brick                >= 2.4
                    , bytestring           >= 0.11.4
                    , containers           >= 0.6.7
                    , directory            >= 1.3.8
                    , effectful-core       >= 2.7
                    , filepath             >= 1.4.100
                    , mpd-protocol         >= 1.0.0.0
                    , network              >= 3.1.2
                    , optics-core          >= 0.4.1
                    , optparse-applicative >= 0.18
                    , stm                  >= 2.5.1
                    , text                 >= 2.0.2
                    , time                 >= 1.12
                    , vty                  >= 6.2
                    , vty-unix             >= 0.2
                    , yamlet               >= 1.0

    hs-source-dirs:  src

    exposed-modules: Reprise.Action
                     Reprise.App
                     Reprise.Config
                     Reprise.Effect.Mpd
                     Reprise.Effect.MpdRequest
                     Reprise.Effect.UiRequest
                     Reprise.Event
                     Reprise.Format
                     Reprise.Handler
                     Reprise.Keymap
                     Reprise.Keys
                     Reprise.Main
                     Reprise.Mpd.Address
                     Reprise.Mpd.Mirror
                     Reprise.Mpd.Worker
                     Reprise.Screen.Help
                     Reprise.State
                     Reprise.Style
                     Reprise.UI.Layout
                     Reprise.UI.SongList
                     Reprise.Width

    c-sources:       cbits/width.c

    other-modules:   Paths_reprise
    autogen-modules: Paths_reprise

executable reprise
    import:         language

    ghc-options:    -threaded

    build-depends:    base
                    , reprise
                    , stm

    hs-source-dirs: app
    main-is:        Main.hs

test-suite test
    import:         language

    ghc-options:    -threaded

    build-depends:    base
                    , bytestring
                    , containers
                    , effectful-core
                    , filepath
                    , mpd-protocol
                    , mpd-test-server
                    , optics-core
                    , QuickCheck
                    , reprise
                    , stm
                    , tasty
                    , tasty-golden
                    , tasty-hunit
                    , tasty-quickcheck
                    , text
                    , vty

    hs-source-dirs: tests

    type:           exitcode-stdio-1.0
    main-is:        Main.hs

    other-modules:  ActionTests
                    AddressTests
                    ConfigTests
                    FormatTests
                    HandlerTests
                    HelpTests
                    KeymapTests
                    KeysTests
                    LayoutTests
                    MirrorTests
                    StyleTests
                    WidthTests
                    WorkerTests
                    Utils
