cabal-version:      3.8
build-type:         Simple
name:               mpd-test-server
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
category:           Testing
maintainer:         andrzej@rybczak.net
author:             Andrzej Rybczak
synopsis:           A real MPD server for tests.

description:
  Starts @mpd@ in a temporary directory, with a @null@ audio output and silent
  FLAC files that the @flac@ tool generates. The test suites of
  @mpd-protocol@ and @reprise@ use it. It is not released.

tested-with: GHC ^>= { 9.6, 9.8, 9.10, 9.12, 9.14 }

common language
    ghc-options:        -Wall
                        -Wcompat
                        -Werror=missing-deriving-strategies
                        -Werror=name-shadowing
                        -Werror=prepositive-qualified-module

    default-language:   GHC2021

    default-extensions: DataKinds
                        DeepSubsumption
                        DerivingStrategies
                        DuplicateRecordFields
                        LambdaCase
                        MultiWayIf
                        NoFieldSelectors
                        NoStarIsType
                        OverloadedRecordDot
                        OverloadedStrings
                        RoleAnnotations
                        StrictData
                        TypeFamilies
                        UndecidableInstances

library
    import:         language

    build-depends:    base                >= 4.18      && < 5
                    , bytestring          >= 0.11.4
                    , directory           >= 1.3.8
                    , filepath            >= 1.4.100
                    , network             >= 3.1.2
                    , process             >= 1.6.17
                    , temporary           >= 1.3
                    , text                >= 2.0.2

    hs-source-dirs:  src

    exposed-modules: MPD.TestServer
